Restaurant-Website
emmanuellekamwa/Restaurant-Website pull request #1
Opened 2021-06-23 10:14 UTC by emmanuellekamwa

In this project I have used the knowledge of DOM manipulation and webpack to build this simple restaurant website.

2021-06-23 11:08 UTC, bellom requested changes
## Hi @emmanuellekamwa  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**1. This project comes after the introduction of the ES6 class keyword, ES6 modules, and Webpack. The main goal of this project is for you to show the understanding of the benefits of modularized code as well as the ability to set up a javascript application made of different modules using Webpack.**

_I can't run `npm run build` to generate `dist folder`, I should be able to run `npm run build` to generate `dist folder` at my end, currently using the one created by you, shouldn't be like that. kindly set up the Webpack properly. checkout [Webpack Setting](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/javascript/lessons/webpack)_

**2. Kindly add a live demo link to your README file.**

**3. Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-06-23 11:08 UTC, bellom commented on src/scripts/contact.js
> +        '<span><i class="fas fa-envelope"></i>emmanuellekamwa@gmail.com</span><span><i class="fab fa-twitter"></i>@AlixKamwa</span><span><i class="fab fa-github"></i>emmanuellekamwa</span>';
We need to use `document.createElement` and `document.appendChild` to appends HTML elements.

2021-06-23 11:08 UTC, bellom commented on src/scripts/contact.js
> +/* eslint-disable indent */
Inline comment: 
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

If you are using VSCode, you can delete the inline comment and hover over the error(configure Eslint checks locally). And you will see your options. Click on the more info button that will take you to a GitHub repo where it is explained why you are getting this error. I find this feature very educational. Please, try to learn and implement the necessary rules so you don't have to keep this disabling line on top of each file. I believe you can do this! 💪😇.

2021-06-23 11:08 UTC, bellom commented on src/scripts/index.js
> +/* eslint-disable quotes */
Inline comment: 
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

2021-06-23 11:08 UTC, bellom commented on src/scripts/loadingpage.js
> +/* eslint-disable linebreak-style */
Inline comment: 
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

2021-06-23 11:08 UTC, bellom commented on src/scripts/menu.js
> +/* eslint-disable linebreak-style */
Inline comment: 
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

If you are using VSCode, you can delete the inline comment and hover over the error(configure Eslint checks locally). And you will see your options. Click on the more info button that will take you to a GitHub repo where it is explained why you are getting this error. I find this feature very educational. Please, try to learn and implement the necessary rules so you don't have to keep this disabling line on top of each file. I believe you can do this! 💪😇

2021-06-23 11:08 UTC, bellom commented on src/scripts/menu.js
> +        "<h1>EXOTIC MENU</h1><h2>Suchi Rolls</h2><ul><li>Maki Mix  <span>7,00£</span></li><li>Suchi Vegeterian <span>7,50£</span></li><li>Sashimi Zalm <span>6,00£</span></li>Urakami Box<li><span>18,0
We need to use `document.createElement` and `document.appendChild` to appends HTML elements.

2021-06-25 16:35 UTC, taiwo2 approved these changes
# STATUS : APPROVED ✔👌🎉
@emmanuellekamwa,  Weldone and nice job for implementing suggested changes.
you can merge and prepare for your next  task

2021-06-25 17:27 UTC, merged